---
apiVersion: v1
kind: Namespace
metadata:
  name: limited

---
apiVersion: v1
kind: ResourceQuota
metadata:
 name: limited-resources
 namespace: limited
spec:
  hard:
    requests.cpu: 500m
    requests.memory: 1024Mi
    limits.cpu: 750m
    limits.memory: 1280Mi
    pods: 5

---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: limited
  labels:
    app: hello
spec:
  selector:
    app: hello
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: limited-ingress 
  namespace: limited 
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: limited.allir.org
      http:
        paths:
          - path: /
            backend:
              serviceName: hello 
              servicePort: 80 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: limited
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: allir/hello-go
          ports: 
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 25Mi

