apiVersion: v1
data:
  url: http://ghost.allir.org
  database__client: mysql
  database__connection__database: ghost
  database__connection__host: ghost-db
kind: ConfigMap
metadata:
  name: ghost-web-config
  namespace: ghost

