---
apiVersion: v1
kind: Namespace
metadata:
  name: limited

---
apiVersion: v1
kind: ResourceQuota
metadata:
 name: limited-resources
 namespace: limited
spec:
  hard:
    requests.cpu: 500m
    requests.memory: 1024Mi
    limits.cpu: 750m
    limits.memory: 1280Mi
    pods: 5

